import './globals.css'
import { Inter, Quicksand } from 'next/font/google'
import '../css/main.css'
import Header from '@/components/Main/Header'
import List from '@/components/Main/List'
import SearchPendingHistory from '@/components/History/SearchPendingHistory'
import Alert from '@/atoms/Alert'
import ModalConfirm from '@/components/Modal/ModalConfirm'
const inter = Inter({ subsets: ['latin'] })
const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} body`}>
        <Header />
        <Alert />
        <ModalConfirm />
        <SearchPendingHistory />
        {children}
        <List />
      </body>
    </html>
  )
}
